# Generated by Django 4.2.11 on 2024-05-22 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('suv', 'Suv'), ('miejski', 'Miejski'), ('terenowy', 'Terenowy'), ('van', 'Van'), ('sportowy', 'Sportowy')], default=None, max_length=50, verbose_name='Kategoria'),
            preserve_default=False,
        ),
    ]
